site_name: UXFlight
site_url: https://UXFlight.github.io/lab-docs/
repo_url: https://github.com/UXFlight/lab-docs

theme:
  name: material
  language: fr
  logo: img/favicon.png
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.suggest
    - content.action.edit
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: "#111111"
      toggle:
        icon: material/weather-night
        name: Passer au mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "#c41f1f"
      accent: "#f5f5f5"
      toggle:
        icon: material/weather-sunny
        name: Passer au mode clair
  logo: img/favicon.png

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.tabbed

plugins:
  - search
  - i18n:
      languages:
        - locale: fr
          name: Français
          default: true
          build: true
        - locale: en
          name: English
          build: true

nav:
  - Accueil: index.md
  - À propos: about.md
  - Projets: projects.md

extra:
  favicon: img/favicon.png

extra_css:
  - css/custom.css
