site_name: CPDLC Research Program
site_url: https://CPDLC-research-program.github.io/lab-docs/
repo_url: https://github.com/CPDLC-research-program/lab-docs
theme:
  name: material
  language: fr
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top

nav:
  - Accueil: index.md
  - À propos: about.md
  - Projets: projects.md
  - Contribuer: contribute.md
  - Templates: templates.md
  - Équipe: team.md
