site_name: UXFlight
site_url: https://UXFlight.github.io/lab-docs/
repo_url: https://github.com/UXFlight/lab-docs

theme:
  name: material
  language: fr
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.suggest
    - content.action.edit
    - content.tabs.link
  logo: img/favicon.png
  favicon: img/favicon.png
  palette:
    - scheme: default
      primary: blue
      accent: amber
      toggle:
        icon: material/weather-night
        name: Passer au mode sombre
    - scheme: slate
      primary: blue
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Passer au mode clair

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.tabbed

plugins:
  - search
  - i18n:
      languages:
        - locale: fr
          name: Français
          default: true
          build: true
        - locale: en
          name: English
          build: true

nav:
  - Accueil: index.md
  - À propos: about.md
  - Projets: projects.md

extra:
  favicon: img/favicon.png

extra_css:
  - css/custom.css